languageCode = "es"
languageName = "Español"
weight = 1
title = "DIMELA.mx"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Tortilla.studio"
  email = "hola@tortilla.studio"
  image = "img/blowfish_logo.png"
  headline = "author_Headline"
  bio = "Author_bio"
  links = [
    { github = "https://github.com/tortillastudio" },
  ]