theme = "blowfish"

baseURL = 'https://rohernandezz.github.io/DIMELA.mx'
languageCode = 'es'
title = 'DIMELA: Directorio Mexicano de Letristas'

enableEmoji = true
removePathAccents = true

[taxonomies]
  servicio = "servicios"
  estado   = "estado"

[minify]
# js = true  # Uncomment to enable JS minification later
# css = true  # Uncomment to enable CSS minification later