backend:
  name: git-gateway
  branch: Netlify # Branch to update (optional; defaults to master)

media_folder: "content/assets"        # Where uploaded media goes in repo
public_folder: "/assets"              # Path used by the site when serving

collections:
  - name: "Directorio"
    label: "entrada del Directorio"
    folder: "content/Directorio"
    create: true
    slug: "{{slug}}"                   # Each entry = its own folder
    path: "{{slug}}/index"             # Ensures index.md inside folder
    media_folder: ""                   # Override: upload inside post folder
    public_folder: ""

    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }

      - label: "Featured Image"
        name: "featured"
        widget: "image"
        choose_url: false
        allow_multiple: false
        media_library:
          config:
            multiple: false
        # Optional pattern validation to enforce a name
        pattern:
          - "featured\\.png$"
          - "The image must be named 'featured.png'"
