backend:
  name: git-gateway
  branch: Netlify  # or your default branch, e.g. "master"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "directorio"
    label: "Directorio"
    folder: "content/Directorio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
